// Code generated by ogen, DO NOT EDIT.

package oas

type APIKey struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKey) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKey) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKey) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetProductBadRequest Error

func (*GetProductBadRequest) getProductRes() {}

type GetProductNotFound Error

func (*GetProductNotFound) getProductRes() {}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProductImage returns new OptProductImage with value set to v.
func NewOptProductImage(v ProductImage) OptProductImage {
	return OptProductImage{
		Value: v,
		Set:   true,
	}
}

// OptProductImage is optional ProductImage.
type OptProductImage struct {
	Value ProductImage
	Set   bool
}

// IsSet returns true if OptProductImage was set.
func (o OptProductImage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProductImage) Reset() {
	var v ProductImage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProductImage) SetTo(v ProductImage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProductImage) Get() (v ProductImage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProductImage) Or(d ProductImage) ProductImage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Order
type Order struct {
	ID        OptString   `json:"id"`
	Total     OptFloat64  `json:"total"`
	Discounts OptFloat64  `json:"discounts"`
	Items     []OrderItem `json:"items"`
	Products  []Product   `json:"products"`
}

// GetID returns the value of ID.
func (s *Order) GetID() OptString {
	return s.ID
}

// GetTotal returns the value of Total.
func (s *Order) GetTotal() OptFloat64 {
	return s.Total
}

// GetDiscounts returns the value of Discounts.
func (s *Order) GetDiscounts() OptFloat64 {
	return s.Discounts
}

// GetItems returns the value of Items.
func (s *Order) GetItems() []OrderItem {
	return s.Items
}

// GetProducts returns the value of Products.
func (s *Order) GetProducts() []Product {
	return s.Products
}

// SetID sets the value of ID.
func (s *Order) SetID(val OptString) {
	s.ID = val
}

// SetTotal sets the value of Total.
func (s *Order) SetTotal(val OptFloat64) {
	s.Total = val
}

// SetDiscounts sets the value of Discounts.
func (s *Order) SetDiscounts(val OptFloat64) {
	s.Discounts = val
}

// SetItems sets the value of Items.
func (s *Order) SetItems(val []OrderItem) {
	s.Items = val
}

// SetProducts sets the value of Products.
func (s *Order) SetProducts(val []Product) {
	s.Products = val
}

func (*Order) placeOrderRes() {}

// Ref: #/components/schemas/OrderItem
type OrderItem struct {
	// ID of the product.
	ProductId OptString `json:"productId"`
	// Item count.
	Quantity OptInt `json:"quantity"`
}

// GetProductId returns the value of ProductId.
func (s *OrderItem) GetProductId() OptString {
	return s.ProductId
}

// GetQuantity returns the value of Quantity.
func (s *OrderItem) GetQuantity() OptInt {
	return s.Quantity
}

// SetProductId sets the value of ProductId.
func (s *OrderItem) SetProductId(val OptString) {
	s.ProductId = val
}

// SetQuantity sets the value of Quantity.
func (s *OrderItem) SetQuantity(val OptInt) {
	s.Quantity = val
}

// Place a new order.
// Ref: #/components/schemas/OrderReq
type OrderReq struct {
	// Optional promo code applied to the order.
	CouponCode OptString           `json:"couponCode"`
	Items      []OrderReqItemsItem `json:"items"`
}

// GetCouponCode returns the value of CouponCode.
func (s *OrderReq) GetCouponCode() OptString {
	return s.CouponCode
}

// GetItems returns the value of Items.
func (s *OrderReq) GetItems() []OrderReqItemsItem {
	return s.Items
}

// SetCouponCode sets the value of CouponCode.
func (s *OrderReq) SetCouponCode(val OptString) {
	s.CouponCode = val
}

// SetItems sets the value of Items.
func (s *OrderReq) SetItems(val []OrderReqItemsItem) {
	s.Items = val
}

type OrderReqItemsItem struct {
	// ID of the product.
	ProductId string `json:"productId"`
	// Item count.
	Quantity int `json:"quantity"`
}

// GetProductId returns the value of ProductId.
func (s *OrderReqItemsItem) GetProductId() string {
	return s.ProductId
}

// GetQuantity returns the value of Quantity.
func (s *OrderReqItemsItem) GetQuantity() int {
	return s.Quantity
}

// SetProductId sets the value of ProductId.
func (s *OrderReqItemsItem) SetProductId(val string) {
	s.ProductId = val
}

// SetQuantity sets the value of Quantity.
func (s *OrderReqItemsItem) SetQuantity(val int) {
	s.Quantity = val
}

type PlaceOrderBadRequest Error

func (*PlaceOrderBadRequest) placeOrderRes() {}

type PlaceOrderForbidden Error

func (*PlaceOrderForbidden) placeOrderRes() {}

type PlaceOrderUnauthorized Error

func (*PlaceOrderUnauthorized) placeOrderRes() {}

type PlaceOrderUnprocessableEntity Error

func (*PlaceOrderUnprocessableEntity) placeOrderRes() {}

// Ref: #/components/schemas/Product
type Product struct {
	ID   OptString `json:"id"`
	Name OptString `json:"name"`
	// Selling price.
	Price    OptFloat32      `json:"price"`
	Category OptString       `json:"category"`
	Image    OptProductImage `json:"image"`
}

// GetID returns the value of ID.
func (s *Product) GetID() OptString {
	return s.ID
}

// GetName returns the value of Name.
func (s *Product) GetName() OptString {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *Product) GetPrice() OptFloat32 {
	return s.Price
}

// GetCategory returns the value of Category.
func (s *Product) GetCategory() OptString {
	return s.Category
}

// GetImage returns the value of Image.
func (s *Product) GetImage() OptProductImage {
	return s.Image
}

// SetID sets the value of ID.
func (s *Product) SetID(val OptString) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Product) SetName(val OptString) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *Product) SetPrice(val OptFloat32) {
	s.Price = val
}

// SetCategory sets the value of Category.
func (s *Product) SetCategory(val OptString) {
	s.Category = val
}

// SetImage sets the value of Image.
func (s *Product) SetImage(val OptProductImage) {
	s.Image = val
}

func (*Product) getProductRes() {}

// Ref: #/components/schemas/ProductImage
type ProductImage struct {
	Thumbnail OptString `json:"thumbnail"`
	Mobile    OptString `json:"mobile"`
	Tablet    OptString `json:"tablet"`
	Desktop   OptString `json:"desktop"`
}

// GetThumbnail returns the value of Thumbnail.
func (s *ProductImage) GetThumbnail() OptString {
	return s.Thumbnail
}

// GetMobile returns the value of Mobile.
func (s *ProductImage) GetMobile() OptString {
	return s.Mobile
}

// GetTablet returns the value of Tablet.
func (s *ProductImage) GetTablet() OptString {
	return s.Tablet
}

// GetDesktop returns the value of Desktop.
func (s *ProductImage) GetDesktop() OptString {
	return s.Desktop
}

// SetThumbnail sets the value of Thumbnail.
func (s *ProductImage) SetThumbnail(val OptString) {
	s.Thumbnail = val
}

// SetMobile sets the value of Mobile.
func (s *ProductImage) SetMobile(val OptString) {
	s.Mobile = val
}

// SetTablet sets the value of Tablet.
func (s *ProductImage) SetTablet(val OptString) {
	s.Tablet = val
}

// SetDesktop sets the value of Desktop.
func (s *ProductImage) SetDesktop(val OptString) {
	s.Desktop = val
}
