// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetProduct implements getProduct operation.
//
// Returns a single product.
//
// GET /product/{productId}
func (UnimplementedHandler) GetProduct(ctx context.Context, params GetProductParams) (r GetProductRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProducts implements listProducts operation.
//
// Get all products available for order.
//
// GET /product
func (UnimplementedHandler) ListProducts(ctx context.Context) (r []Product, _ error) {
	return r, ht.ErrNotImplemented
}

// PlaceOrder implements placeOrder operation.
//
// Place a new order in the store.
//
// POST /order
func (UnimplementedHandler) PlaceOrder(ctx context.Context, req *OrderReq) (r PlaceOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}
