// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikey.sql

package dbgen

import (
	"context"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_hash, name, scopes
FROM api_keys
WHERE key_hash = $1 AND active = TRUE
`

type GetAPIKeyByHashRow struct {
	ID      string   `db:"id" json:"id"`
	KeyHash string   `db:"key_hash" json:"key_hash"`
	Name    string   `db:"name" json:"name"`
	Scopes  []string `db:"scopes" json:"scopes"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
	)
	return i, err
}

const upsertAPIKey = `-- name: UpsertAPIKey :exec
INSERT INTO api_keys (id, key_hash, name, scopes, active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    key_hash = EXCLUDED.key_hash,
    name = EXCLUDED.name,
    scopes = EXCLUDED.scopes,
    active = EXCLUDED.active
`

type UpsertAPIKeyParams struct {
	ID      string   `db:"id" json:"id"`
	KeyHash string   `db:"key_hash" json:"key_hash"`
	Name    string   `db:"name" json:"name"`
	Scopes  []string `db:"scopes" json:"scopes"`
	Active  bool     `db:"active" json:"active"`
}

func (q *Queries) UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, upsertAPIKey,
		arg.ID,
		arg.KeyHash,
		arg.Name,
		arg.Scopes,
		arg.Active,
	)
	return err
}
