// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupon.sql

package dbgen

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT code, discount_type, value, min_items, description
FROM coupons
WHERE code = UPPER($1) AND active = TRUE
`

type GetCouponByCodeRow struct {
	Code         string          `db:"code" json:"code"`
	DiscountType string          `db:"discount_type" json:"discount_type"`
	Value        decimal.Decimal `db:"value" json:"value"`
	MinItems     int32           `db:"min_items" json:"min_items"`
	Description  string          `db:"description" json:"description"`
}

func (q *Queries) GetCouponByCode(ctx context.Context, upper interface{}) (GetCouponByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, upper)
	var i GetCouponByCodeRow
	err := row.Scan(
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinItems,
		&i.Description,
	)
	return i, err
}

const upsertCoupon = `-- name: UpsertCoupon :exec
INSERT INTO coupons (code, discount_type, value, min_items, description, active)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code) DO UPDATE SET
    discount_type = EXCLUDED.discount_type,
    value = EXCLUDED.value,
    min_items = EXCLUDED.min_items,
    description = EXCLUDED.description,
    active = EXCLUDED.active
`

type UpsertCouponParams struct {
	Code         string          `db:"code" json:"code"`
	DiscountType string          `db:"discount_type" json:"discount_type"`
	Value        decimal.Decimal `db:"value" json:"value"`
	MinItems     int32           `db:"min_items" json:"min_items"`
	Description  string          `db:"description" json:"description"`
	Active       bool            `db:"active" json:"active"`
}

func (q *Queries) UpsertCoupon(ctx context.Context, arg UpsertCouponParams) error {
	_, err := q.db.Exec(ctx, upsertCoupon,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MinItems,
		arg.Description,
		arg.Active,
	)
	return err
}
