// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package dbgen

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, items, total, discounts, coupon_code)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderParams struct {
	ID         string          `db:"id" json:"id"`
	Items      []byte          `db:"items" json:"items"`
	Total      decimal.Decimal `db:"total" json:"total"`
	Discounts  decimal.Decimal `db:"discounts" json:"discounts"`
	CouponCode string          `db:"coupon_code" json:"coupon_code"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.Items,
		arg.Total,
		arg.Discounts,
		arg.CouponCode,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, items, total, discounts, coupon_code, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Items,
		&i.Total,
		&i.Discounts,
		&i.CouponCode,
		&i.CreatedAt,
	)
	return i, err
}
