// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package dbgen

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price, category, image_thumbnail, image_mobile, image_tablet, image_desktop FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.ImageThumbnail,
		&i.ImageMobile,
		&i.ImageTablet,
		&i.ImageDesktop,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, category, image_thumbnail, image_mobile, image_tablet, image_desktop FROM products ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Category,
			&i.ImageThumbnail,
			&i.ImageMobile,
			&i.ImageTablet,
			&i.ImageDesktop,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (id, name, price, category, image_thumbnail, image_mobile, image_tablet, image_desktop)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    image_thumbnail = EXCLUDED.image_thumbnail,
    image_mobile = EXCLUDED.image_mobile,
    image_tablet = EXCLUDED.image_tablet,
    image_desktop = EXCLUDED.image_desktop
`

type UpsertProductParams struct {
	ID             string          `db:"id" json:"id"`
	Name           string          `db:"name" json:"name"`
	Price          decimal.Decimal `db:"price" json:"price"`
	Category       string          `db:"category" json:"category"`
	ImageThumbnail string          `db:"image_thumbnail" json:"image_thumbnail"`
	ImageMobile    string          `db:"image_mobile" json:"image_mobile"`
	ImageTablet    string          `db:"image_tablet" json:"image_tablet"`
	ImageDesktop   string          `db:"image_desktop" json:"image_desktop"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Category,
		arg.ImageThumbnail,
		arg.ImageMobile,
		arg.ImageTablet,
		arg.ImageDesktop,
	)
	return err
}
